$(OBJDIR)/jetyr.o : jetyr.f90 
$(OBJDIR)/hl2myr.o : hl2myr.f90 
$(OBJDIR)/get_tokyr.o : get_tokyr.f90 
$(OBJDIR)/st40yr.o : st40yr.f90 
$(OBJDIR)/ssspyr.o : ssspyr.f90 
$(OBJDIR)/nstxyr.o : nstxyr.f90 
$(OBJDIR)/staryr.o : staryr.f90 
$(OBJDIR)/mkbeastid.o : mkbeastid.f90 
$(OBJDIR)/stepyr.o : stepyr.f90 
$(OBJDIR)/arcyr.o : arcyr.f90 
$(OBJDIR)/mastyr.o : mastyr.f90 
$(OBJDIR)/glmtyr.o : glmtyr.f90 
$(OBJDIR)/eastyr.o : eastyr.f90 
$(OBJDIR)/augdyr.o : augdyr.f90 
$(OBJDIR)/demoyr.o : demoyr.f90 
$(OBJDIR)/ste1yr.o : ste1yr.f90 
$(OBJDIR)/pi3yr.o : pi3yr.f90 
$(OBJDIR)/tcabyr.o : tcabyr.f90 
$(OBJDIR)/shpdyr.o : shpdyr.f90 
$(OBJDIR)/st80yr.o : st80yr.f90 
$(OBJDIR)/sprcyr.o : sprcyr.f90 
$(OBJDIR)/tcvyr.o : tcvyr.f90 
$(OBJDIR)/tftryr.o : tftryr.f90 
$(OBJDIR)/kstryr.o : kstryr.f90 
$(OBJDIR)/checkid.o : checkid.f90 
$(OBJDIR)/d3dyr.o : d3dyr.f90 
$(OBJDIR)/arisyr.o : arisyr.f90 
$(OBJDIR)/iteryr.o : iteryr.f90 
$(OBJDIR)/nstuyr.o : nstuyr.f90 
$(OBJDIR)/ltxyr.o : ltxyr.f90 
$(OBJDIR)/smrtyr.o : smrtyr.f90 
$(OBJDIR)/westyr.o : westyr.f90 
