C******************** START FILE FIXGEO.FOR ; GROUP PLOTR4 ******************
C---------------------------------------------------------------
C  FIXGEO
C
C  SET UP METRIC FOR INTEGRATION/AVERAGING OF RADIAL PROFILE FCNS
C
C   ... DVOL = ZONE VOLUME ELEMENTS
C   ... DAREA = AREA (CROSS-SECTIONAL) ELEMENTS
C   ... DRAV = "AVERAGE" DR ELEMENT
C   ... SURF = ZONE BDY SURFACE AREA
C
C  IF NLXVAR IS .FALSE. OR NLXVAR IS .TRUE. BUT THE FCNS "DVOL",
C   ETC. ARE NOT IN THE MF DATA, THESE METRICS ARE CONSTANT IN
C   TIME.  OTHERWISE THEY ARE TIME VARYING AND MUST BE PICKED UP
C   DIRECTLY FROM THE MF FILE
C
      SUBROUTINE FIXGEO
C
      use cplotr_mod
C
      DATA ZPI/3.14159/
C
C  LOAD DEFAULT FLAG SETTINGS
      DO 10 I=1,NXR
        NFX(I)=0
        NLXFOT(I)=.FALSE.
        NLXFTD(I)=.FALSE.
        NLXMON(I)=.TRUE.
        XPATCH(I)=0.0
 10   CONTINUE
C
      IF(NLXVAR) GO TO 100
C
C  DEFINE METRICS FROM DATA ALREADY READ IN FROM TF OR MF FILE
C   THEY DO NOT VARY IN TIME
C
 25   CONTINUE
      ZRBI=0.0
      IZONEX=NZONEX(1)
      DO 30 I=1,IZONEX
        ZRBO=XARRY(I,2)
        ZRC=XARRY(I,1)
        ZRDR=ZRC*(ZRBO-ZRBI)
        DAREA(I)=2.0*ZPI*ZRDR
        DVOL(I)=2.0*ZPI*RMAJOR*DAREA(I)
        DRAV(I)=ZRBO-ZRBI
        SURF(I)=2.0*ZPI*RMAJOR*2.0*ZPI*ZRBO
C
        ZRBI=ZRBO
 30   CONTINUE
      NLTGEO=.FALSE.
      GO TO 300
C
 100  CONTINUE
C  X AXIS VALUES ARE IN MF FILE, LABELS ALREADY READ FROM TF FILE
C  PUT LABELS IN X AXIS LABEL ARRAYS
      DO 110 J=1,NXR
        DO 105 I=1,NFXT
          IF(ABR(I).EQ.XNDABB(J)) GO TO 106
 105    CONTINUE
        I=0
 106    CONTINUE
        IFCN=I
        NFX(J)=IFCN
C
        XLAB(J)=LABELR(IFCN)
        XLABU(J)=UNITSR(IFCN)
 110  CONTINUE
C
C  NOW CHECK FOR TIME VARYING GEOMETRY.  IF ABSENT ASSUME THE X
C  AXES ARE FIXED IN TIME (VALID DUE TO HISTORY OF TRANSP CODE)
C
C  IF FUNCTION "DVOL" IS IN MF FILE GEOMETRY IS ASSUMED TIME VARYING
C
      LDVOL=0
      LDAREA=0
      LSURF=0
      LDRAV=0
      LDRAVFAC=0
C
      LX=0
      LXB=0
C
      DO 120 I=1,NFXT
        IF(ABR(I).EQ.'DVOL') LDVOL=I
        IF(ABR(I).EQ.'DAREA') LDAREA=I
        IF(ABR(I).EQ.'SURF') LSURF=I
        IF(ABR(I).EQ.'DRAV') LDRAV=I
        if(abr(i).eq.'DRAVFAC') LDRAVFAC=I
        if(abr(i).eq.'X') LX=I
        if(abr(i).eq.'XB') LXB=I
 120  CONTINUE
C
      LELDOT=0
      do i=1,nft
         if(ABT(i).eq.'ELDOT') LELDOT=i
      enddo
C
      IF(LDVOL.NE.0 .or. .NOT.NLTRANSP) GO TO 200
C
C  NO TIME VARYING GEOMETRY.  READ X AXIS VALUE FROM LAST TIME IN FILE
C
      IT=NTR
      DO 130 J=1,NXR
        ISIZE=NZONEX(J)
        CALL READMF(IT,NFX(J),XARRY(1,J),ISIZE)
 130  CONTINUE
C  NOW DEFINE METRIC FOR NON-TIME VARYING 1D GEOMETRY IN DEFAULT
C  MANNER
      write(6,*)
     >   ' **fixgeo** warning:  NLXVAR = .FALSE. -- ancient run.'
      NLXVAR=.FALSE.
      GO TO 25
C-------------------------
 200  CONTINUE
C
C  GEOMETRY IS A FUNCTION OF TIME
C
      DO 210 J=1,NXR
        NLXFOT(J)=.TRUE.
        NLXFTD(J)=.TRUE.
 210  CONTINUE
C
      NLTGEO=.TRUE.
C-----------------------------------
C  SAVE DEFAULT X AXIS LABELS AND EXIT
C
 300  CONTINUE
      DO 310 J=1,NXR
        XLABD(J)=XLAB(J)
        XLABDU(J)=XLABU(J)
 310  CONTINUE
C
      RETURN
      END
C******************** END FILE FIXGEO.FOR ; GROUP PLOTR4 ******************
