C******************** START FILE INDORD.FOR ; GROUP LSIGEN ******************
C-------------------------------------------------------------
C  INDORD
C
C  BUILD ALPHABETIC ORDER OF ENTRIES IN INDEX
C
C  USE BINARY SEARCH ALGORITHM TO LOCATE ALPHABETIC POSITION
C  OF NEXT NEW ENTRY
C
      SUBROUTINE INDORD(INUM)
C
C  INSERT ENTRY INUM IN ALPHABETIC ORDER IN LIST
C
      use cplotr_mod
C
C  PUT NEW ENTRY AT END OF LIST ???
C
      IF(INUM.EQ.1) GO TO 50
C
      IPREV=LSINDX(INUM-1)
C
      IF(LSLABL(INUM).LT.LSLABL(IPREV)) GO TO 100
C
C  INSERT ENTRY AT END OF LIST
C
 50   CONTINUE
      LSINDX(INUM)=INUM
      RETURN
C
C  DO BINARY SEARCH TO FIND WHERE TO INSERT ENTRY
C
 100  CONTINUE
C  ITOP,IBOT DELIMIT RANGE YET TO BE SEARCHED
      ITOP=1
      IBOT=INUM-1
C
 110  CONTINUE
C
      IMID=(ITOP+IBOT)/2
C
      INDMID=LSINDX(IMID)
C
      IF(LSLABL(INUM).LT.LSLABL(INDMID)) GO TO 140
      GO TO 150
C
 140  CONTINUE
C  IN TOP HALF
      IBOT=IMID
C  DONE ?
      IF(IBOT.EQ.ITOP) GO TO 200
      GO TO 110
C
 150  CONTINUE
C  BOTTOM HALF
      ITOP=IMID+1
      IF(ITOP.LE.IBOT) GO TO 110
C  TROUBLE
      write(lunzer(0),9901)
 9901 FORMAT(/' ??? ERROR IN BINARY SEARCH ALPHABETIZATION'/
     >   '     ALGORITHM-- S.R. "INDORD" FILE "[TRANSP]LSIGEN.FOR"')
      call abortt
C
C  FOUND LOCATION; INSERT ENTRY
C
 200  CONTINUE
      IN1=ITOP+1
      IN2=INUM
      DO 210 I=IN2,IN1,-1
      LSINDX(I)=LSINDX(I-1)
 210  CONTINUE
      LSINDX(ITOP)=INUM
      RETURN
      END
C******************** END FILE INDORD.FOR ; GROUP LSIGEN ******************
