C******************** START FILE IXCALC.FOR ; GROUP IXCALC ******************
C------------------------------
C  IXCALC
 
 
 
      SUBROUTINE IXCALC(ZF1,ZF2,INX,ZSGN,IINT,IT,ZX0L,ZF0)
 
 
C  Updated:
C
C  11/16/93 TBT - Back out of 9/93 change.
C  09/28/93 TBT - Set result to zero if differential in divisor is 0.0
 
C  ADDED D. MC CUNE MAY 1983-- GRADIENT/SCALE LENGTH CALCULATIONS.
C      DL ELEMENTS REQUIRED
 
 
C   --------------------------------------------------------------
C
C  CALCULATE VARIOUS INTEGRALS AND INTEGRAL AVERAGES REQUIRED BY
C  PLOTR.
C
C  GENERAL TYPES OF INTEGRALS SUPPORTED:
C   THOSE UTILIZING DIFFERENTIAL ELEMENTS OF
C      VOLUME
C      LENGTH
C      AREA IN POLOIDAL PLANE
 
C
C  CAPABILITY TO USE TIME VARYING GEOMETRY INFO FROM DATA BUFFER HAS
C  BEEN ADDED.  SEE SUBROUTINE DMGGEO (PLDMGR.FOR)
C
C  INPUT VARIABLES:
C
C  ZF1  LOCAL ARRAY CONTAINING FUNCTION TO BE INTEGRATED OR
C       ROLLING-AVERAGED OR DIFFERENTIATED
C       ** INTEGRAL OPERATORS OVERWRITE THIS ARRAY **
C  INX  DIMENSIONALITY OF ZF
C  IINP  TYPE OF INTEGRAL/AVERAGE TO PERFORM
C    0  NONE
C    1  VOLUME INTEGRAL
C    2  FLUX INTEGRAL
C    3  AREA INTEGRAL
C    4  LINE AVERAGE
C    5  VOLUME AVERAGE
C    6  RMS AVERAGE
C    7  DOUBLE-INVERSE LINE AVERAGE
C    8  DOUBLE-INVERSE VOLUME AVERAGE
C    9  "CTR NORMALIZATION"; MULT BY FACTOR TO MAKE 1ST PT =1
C    10 "MAX NORMALIZATION"; MULT BY FACTOR TO MAKE MAX MOD +/-1
C   -1  GRADIENT
C   -2  LOGARITHMIC DERIVATIVE (INV SCALE LENGTH)
C   -3  SCALE LENGTH
C
C  ZSGN - =1.0 OR -1.0:  MULTIPLY PROFILE BY THIS
C
C  IT= INDEX TO CURRENT TIME-- USED FOR TIME DEPENDENT GEOMETRY
C  ZX0L-- LOCATION OF INTEGRATION LOWER LIMIT
C
C  OUTPUT:  ZF2-- TRANSFORMED PROFILE
C    ZF0-- VALUE OF PROFILE EXTENDED TO INCL. MAGNETIC AXIS
C    (FOR INTEGRAL OPERATORS, IINT.GT.0, ONLY)
 
 
      use datmgr_mod
 
      use cplotr_mod
C
      DIMENSION ZF1(INX),ZF2(INX)
C  LOCAL ARRAYS USED TO SMOOTH OUT AVGS NEAR LOWER LIMIT PTS
      DIMENSION ZFAFIX(3)
C
      dimension zdravfac(NR0)  ! gradient correction dmc Feb 96
C
      LOGICAL MOMRUN
 
      Real ZLmax
      Data ZLmax /1.e15/
 
C
C-----------------------------------------------------------------------
C
C  IF GEOMETRY IS TIME DEPENDENT LOAD NEEDED INFO AT CURRENT TIME
C
      IF(NLTGEO) THEN
C  DL ELEMENTS
        IF(IINT.LT.0) THEN
          IP=NDPTR(LDRAV,INX,IT)
          CALL copyr4(DATBUF(IP),DRAV,INX)
          if(LDRAVFAC.gt.0) then
             ip=ndptr(LDRAVFAC,inx,it)
             call copyr4(datbuf(ip),zdravfac,inx)
          else
             do ix=1,inx
      	  zdravfac(ix)=1.0
             enddo
          endif
        ENDIF
C   VOLUME INTEGRAL OR AVERAGE
        IF((IINT.EQ.1).OR.(IINT.EQ.5).OR.(IINT.EQ.6).OR.
     >     (IINT.EQ.8)) THEN
          IP=NDPTR(LDVOL,INX,IT)
          CALL copyr4(DATBUF(IP),DVOL,INX)
        ENDIF
C   FLUX INTEGRAL
        IF(IINT.EQ.2) THEN
          IP=NDPTR(LDVOL,INX,IT)
          CALL copyr4(DATBUF(IP),DVOL,INX)
          IP=NDPTR(LSURF,INX,IT)
          CALL copyr4(DATBUF(IP),SURF,INX)
        ENDIF
C   AREA INTEGRAL
        IF(IINT.EQ.3) THEN
          IP=NDPTR(LDAREA,INX,IT)
          CALL copyr4(DATBUF(IP),DAREA,INX)
        ENDIF
C   LINE AVERAGE
        IF((IINT.EQ.4).OR.(IINT.EQ.7)) THEN
          IF(MOMRUN(IDUM,IGEO)) THEN
C     COMPUTE MIDPLANE DR'S FROM MOMENTS DATA
            CALL PLMMDR(DRAV,INX,IT)
          ELSE
C     USE TRANSP DR'S
            IP=NDPTR(LDRAV,INX,IT)
            CALL copyr4(DATBUF(IP),DRAV,INX)
          ENDIF
        ENDIF
      ENDIF
C-----------------------------
C  NO OPERATOR:
C
      IF(IINT.NE.0) GO TO 100
      DO 10 IX=1,INX
      ZF2(IX)=ZSGN*ZF1(IX)
 10   CONTINUE
      RETURN
C-----------------------------
 100  CONTINUE
C  RENORM OPERATOR
      IF((IINT.EQ.9).OR.(IINT.EQ.10)) THEN
        IXMIN=1
        IXMAX=1
        DO 105 IX=1,INX
          IF(ABS(ZF1(IXMIN)).GT.ABS(ZF1(IX))) IXMIN=IX
          IF(ABS(ZF1(IXMAX)).LT.ABS(ZF1(IX))) IXMAX=IX
 105    CONTINUE
        IF(ABS(ZF1(IXMAX)).EQ.0.0) THEN
          ZNORM=0.0
        ELSE IF(IINT.EQ.9) THEN
          ZNORM=1.0/(AMAX1(1.E-35,ABS(ZF1(1))))
        ELSE IF(IINT.EQ.10) THEN
          ZNORM=1.0/(AMAX1(1.E-35,ABS(ZF1(IXMAX))))
        ENDIF
        IF(ZNORM.NE.0.0) THEN
          ZTEST=ALOG10(ZNORM)+ALOG10(ABS(ZF1(IXMAX)))
          IF(ZTEST.GT.38.0) ZNORM=1.0
        ENDIF
C
        DO 106 IX=1,INX
          ZF2(IX)=ZSGN*ZNORM*ZF1(IX)
 106    CONTINUE
        RETURN
      ENDIF
C-----------------------------
C  DIFFERENTIAL OPERATOR
C
      ZSMALL=1.E-30
      IF(IINT.GT.0) GO TO 200
C
      INXM1=INX-1
 
      DO 110 IX=1,INXM1
      IXP1=IX+1
      ZDR=0.5*(DRAV(IX)/zdravfac(ix)+DRAV(IXP1)/zdravfac(ixp1))
      ZF2(IX)=ZSGN*(ZF1(IXP1)-ZF1(IX))/ZDR
      IF(IINT.EQ.-1) GO TO 110
C  LOGARITHMIC DERIVATIVE
      ZFA=0.5*(ZF1(IXP1)+ZF1(IX))
C	If (ZFA .Eq. 0.0)  Zf2(Ix)=0.0      ! tbt Backout 11/93
      CALL IXCHK0(ZFA,ZSMALL)
      ZF2(IX)=ZF2(IX)/ZFA
      IF(IINT.EQ.-2) GO TO 110
C  SCALE LENGTH
C	If (ZF2(Ix) .Eq. 0.0)  Go to 110    ! tbt  Keep zero. Backout 11/93
      If (ZF2(Ix) .Eq. 0.0) Then
C	   . grad(f) = 0.0
         ZF2(Ix) = ZLmax
      Else
C	   . grad(f) <> 0.0
C	   CALL IXCHK0(ZF2(IX),ZSMALL)
         ZF2(IX)=1.0/ZF2(IX)
         ZF2(Ix) = Max( -ZLmax, Min( ZLmax, ZF2(Ix)))  ! Bound tbt
      End If   ! Zf2
 110  CONTINUE   ! End do  Ix
 
      ZF2(INX)=ZF2(INXM1)
      RETURN
C------------------------------------
C  INTEGRAL OPERATOR
C
 200  CONTINUE
C
C  INVERT FCN IF DOING DBL INVERSE INTEGRAL
C
      ZSMALL=1.E-30
      IF(IINT.GE.7) THEN
        DO 205 IX=1,INX
          CALL IXCHK0(ZF1(IX),ZSMALL)
          ZF1(IX)=1.0/ZF1(IX)
 205    CONTINUE
      ENDIF
C
C  SQUARE FCN IF DOING RMS AVG
C
      IF(IINT.EQ.6) THEN
        DO 210 IX=1,INX
          ZF1(IX)=ZF1(IX)*ZF1(IX)
 210    CONTINUE
      ENDIF
C
C  DO INITIAL INTEGRATION
C
      IF(IINT.EQ.3) THEN
C  AREA INTEGRAL
        CALL IXCAL0(ZF1,ZF2,DAREA,INX,ZSGN)
      ELSE IF((IINT.EQ.4).OR.(IINT.EQ.7)) THEN
C  LINE INTEGERAL
        CALL IXCAL0(ZF1,ZF2,DRAV,INX,ZSGN)
C  VOLUME INTEGRAL
      ELSE
        CALL IXCAL0(ZF1,ZF2,DVOL,INX,ZSGN)
      ENDIF
C
C  ZF1 NOW CONTAINS INTEGRAL OF 1*DIFF. ELEMENTS (DENOMINATOR FOR
C  AVERAGES); ZF2 CONTAINS THE INTEGRATED FUNCTION
C
C  NOW SHIFT AS PER PASSED INTEGRATION LOWER LIMIT
C
      ZSHIF1=0.0
      ZSHIF2=0.0
      CALL IXSHFT(ZF1,ZF2,INX,ZX0L,ZSHIF1,ZSHIF2)
C
C  EVALUATE ALL AVERAGES.  ZSHIF1, ZSHIF2 ARE INTEGRALS FROM THE
C  LOWER LIMIT PT. TO 0 (THE AXIS)  OF DX AND F*DX RESPECTIVELY
C
C  DEFINE ZF0= THE VALUE OF THE INTEGRAL OPERATION ON AXIS
      ZF0=-ZSHIF2
      IF(IINT.GT.3) THEN
        ZXP=-ZSHIF1
        ZIFP=-ZSHIF2
        ILLFIX=0
        IFLFIX=0
C  DEAL WITH ZF0
        IF(ZX0L.LT.1.) THEN
          ZX0S=-ZX0L
          IX0S=0
          ILLFIX=1
          IFLFIX=1
          ZDX=ZF1(1)-ZXP
          ZFAFIX(1)=(ZF2(1)-ZIFP)/ZDX
        ELSE
          ZF0=ZSHIF2/ZSHIF1
        ENDIF
        DO 220 IX=1,INX
        ZX=ZF1(IX)
        ZIF=ZF2(IX)
        IF(ABS(FLOAT(IX)-ZX0L).LT.1.0) THEN
          IF(ILLFIX.EQ.0) THEN
            ZX0S=FLOAT(IX)-ZX0L
            IX0S=IX
          ENDIF
          ILLFIX=ILLFIX+1
          IFLFIX=1
          ZDX=ZX-ZXP
          ZFAFIX(ILLFIX)=(ZIF-ZIFP)/ZDX
        ELSE
          ZF2(IX)=ZF2(IX)/ZF1(IX)
          IF(IFLFIX.EQ.1) THEN
            IFLFIX=0
            ILLFIX=ILLFIX+1
            ZDX=ZX-ZXP
            ZFAFIX(ILLFIX)=(ZIF-ZIFP)/ZDX
          ENDIF
        ENDIF
        ZIFP=ZIF
        ZXP=ZX
 220    CONTINUE
        IF(IFLFIX.EQ.1) THEN
          ILFP=ILLFIX
          ILLFIX=ILLFIX+1
          ZFAFIX(ILLFIX)=ZFAFIX(ILFP)
        ENDIF
C  FIX PTS IN VICINITY OF LOWER LIMIT OF AVG
C   (WHERE NUMERATOR AND DENOMINATOR OF AVG FORMULA
C    [INTEGRAL]F*DX/[INTEGRAL]DX BOTH TEND TOWARD ZERO
C    L'HOPITAL WAS RIGHT... AND AVG ==> LOCAL VALUE AS EXTENT OF AVG
C    APPROACHES ZERO
        ILLFIX=ILLFIX-1
        IF(ILLFIX.EQ.0) GO TO 226
        DO 225 I=1,ILLFIX
          IX=IX0S+I-1
          IP1=I+1
          ZFAC=1.0-0.5*(1.0+ZX0S+FLOAT(IX-IX0S))
          ZFANS=ZFAFIX(I)+ZFAC*(ZFAFIX(IP1)-ZFAFIX(I))
          IF(IX.GT.0) ZF2(IX)=ZFANS
          IF(IX.EQ.0) ZF0=ZFANS
CT	    TYPE *,IX,ZFAFIX(I),ZFAFIX(IP1),ZFAC,ZF2(IX)
 225    CONTINUE
 226    CONTINUE
      ENDIF
C
C  COMPLETE EVALUATION OF FLUX INTEGRAL
C
      IF(IINT.EQ.2) THEN
        ZF0=ZF0/SURF(1)
        DO 230 IX=1,INX
        ZF2(IX)=ZF2(IX)/SURF(IX)
 230    CONTINUE
      ENDIF
C
C  INVERT BACK IF THIS IS A DBL INVERSE INTEGRAL
C
      IF(IINT.GE.7) THEN
        CALL IXCHK0(ZF0,ZSMALL)
        ZF0=1.0/ZF0
        DO 240 IX=1,INX
        CALL IXCHK0(ZF2(IX),ZSMALL)
        ZF2(IX)=1.0/ZF2(IX)
 240    CONTINUE
      ENDIF
C
C  SQ ROOT BACK IF THIS IS AN RMS AVG
C
      IF(IINT.EQ.6) THEN
        ZF0=SQRT(ZF0)
        DO 250 IX=1,INX
          ZF2(IX)=SQRT(ZF2(IX))
 250    CONTINUE
      ENDIF
C
C  THATS ALL FOLKS
C
      RETURN
      END
C******************** END FILE IXCALC.FOR ; GROUP IXCALC ******************
