C******************** START FILE LSINIT.FOR ; GROUP LSIGEN ******************
C-------------------------------------------------------------
C  D. MC CUNE  10 APR 1981
C  >> LSIGEN <<
C
C  MAKE INDEX-STYLE ALPHABETIZED LISTING OF GRAPHS WITH PAGE
C  REFERENCES.
C   3 SUBROUTINES:
C  (1) LSINIT(LABEL) MAKES A NEW ENTRY IN THE TABLE OF LABELS
C      OF GRAPHS DRAWN, SETS THE INITIAL PAGE AND CLEARS THE
C      NUMBER OF PAGES TO ZERO.  THIS ROUTINE IS CALLED BEFORE
C      CALL TO INTERACTIVE GRAPHICS GENERATING SUBROUTINE
C  (2) LSENTR IS CALLED AFTER GRAPHICS GENERATING SUBROUTINE;
C      IF FINALIZES THE ENTRY INITIALIZED BY LSINIT.  IF THE
C      GRAPHICS GENERATOR DREW NO GRAPHS, THE ENTRY IS DELETED;
C      OTHERWISE THE NUMBER OF PAGES OF GRAPHS DRAWN IS SET.
C  (3) LSIGEN CALCULATES THE ALPHABETIC ORDER OF LABELS OF ALL
C      GRAPHS DRAWN, AND GENERATES A FORMATTED INDEX, USING
C      A-G GRAPHICS STRING TRANSFER ROUTINES AGX___, SO THAT
C      GRAPHICS STYLE INDEX IS GENERATED AND MAY BE PLOTTED
C      ON VERSATEC ALONG WITH STANDARD GRAPHICS OUTPUT
C--------------
C  (1) LSINIT
C     ZLAB-- 20 CHARACTER LABEL
C
      SUBROUTINE LSINIT(ZLABEL,ZUNITS)
C
      use cplotr_mod
C
      CHARACTER*(*) ZLABEL,ZUNITS
C
C  CHECK THAT PREVIOUS ENTRY DOES NOT HAVE SAME NAME
C
      ILEN=MIN0(LEN(ZLABEL),LEN(LSLABL(1)))
C
      IF(NLSENT.EQ.0) GO TO 50
      IF(ZLABEL(1:ILEN).NE.LSLABL(NLSENT)(1:ILEN)) GO TO 50
C
C  CONTINUING CURRENT ENTRY
C
      RETURN
C
C  MAKE NEW ENTRY
C
 50   CONTINUE
      NLSENT=NLSENT+1
C
      LSLABL(NLSENT)=' '
      LSLABL(NLSENT)(1:ILEN)=ZLABEL(1:ILEN)
C
      LSUNTS(NLSENT)=ZUNITS
C
      LSPAGI(NLSENT)=NPAGEG+1
      LSPAGL(NLSENT)=0
C
      RETURN
      	END
C******************** END FILE LSINIT.FOR ; GROUP LSIGEN ******************
