#GNU Makefile to build Library librp_kernel.a 
#
#08/01/00 C. Ludescher
#

ifneq ($(MAKELEVEL),0)
# if OBJ was defined for main Makefile one level down
ifeq ("${OBJ}",".")
	override OBJ=..
endif
endif

# define system dependent flags, etc.
-include ../share/Make.local
include ../share/Make.flags

ifdef DEBUG
	FFLAGS = $(DFFLAGS)
endif


ARC = $(OBJ)/lib/librp_kernel.a
OBJDIR = $(OBJ)/obj/rp_kernel

#=============================================================
 
# fortran archive members
FALL  = $(subst .f,.o, $(wildcard *.f)) $(subst .F,.o, $(wildcard *.F))
MEM = $(foreach file,$(FALL),$(ARC)($(file)))


.PHONY: clean realclean checkdir all exec

libs: FORCE $(ARC)

all:  libs 
	@echo done  

FORCE:
	@test -d $(OBJ)/lib || mkdir -p $(OBJ)/lib
	@test -d $(OBJ)/obj/rp_kernel || mkdir -p $(OBJ)/obj/rp_kernel
	@if test ! -f $(LIBDIR)/librplot_mod.a; then \
	if test -f ../rplot_mod/Makefile; then \
	(cd ../rplot_mod; $(MAKE) libs); fi; fi

$(ARC): $(MEM)
	@$(RANLIB) $@ > /dev/null
 
# compile 
$(ARC)(%.o): %.f
	$(FC) $(FFLAGS) $(MODFLAGS) -I./ $(INCFLAGS) $(OUT)  $(OBJDIR)/$*.o $<
	$(make_ar)

# pre-process/compile fixed fortran code
$(ARC)(%.o): %.F
	$(F_proc)
	$(make_ar)

#
#---------------------------------------------------
exec:
	@echo 

clean: 
	@rm -f $(OBJDIR)/*

realclean: clean
	@rm -f $(ARC)

install:
	@test -d $(LIBDIR) || mkdir -p $(LIBDIR)
	@if test -f $(ARC); then \
	  umask 133; cp $(ARC) $(LIBDIR)/; \
	else test -f $(LIBDIR)/librp_kernel.a || echo ">>> can not find $(ARC)";fi

uninstall:
	rm -f $(LIBDIR)/librp_kernel.a
