$(OBJDIR)/plcocosh.o : plcocosh.for 
$(OBJDIR)/selchk.o : selchk.for 
$(OBJDIR)/rconnect.o : rconnect.for 
$(OBJDIR)/plcfnxct.o : plcfnxct.for 
$(OBJDIR)/indord.o : indord.for 
$(OBJDIR)/rppcpars.o : rppcpars.for 
$(OBJDIR)/trintrp.o : trintrp.for 
$(OBJDIR)/tkbmryrp.o : tkbmryrp.for 
$(OBJDIR)/ixcalc.o : ixcalc.for 
$(OBJDIR)/plcasin.o : plcasin.for 
$(OBJDIR)/idchek.o : idchek.for 
$(OBJDIR)/plcmds.o : plcmds.for 
$(OBJDIR)/plcsub.o : plcsub.for 
$(OBJDIR)/smtima.o : smtima.for 
$(OBJDIR)/plcgetx.o : plcgetx.for 
$(OBJDIR)/plclis.o : plclis.for 
$(OBJDIR)/mgunref.o : mgunref.for 
$(OBJDIR)/findmlti.o : findmlti.for 
$(OBJDIR)/pconnect.o : pconnect.for 
$(OBJDIR)/smargtr.o : smargtr.for 
$(OBJDIR)/mglbsw.o : mglbsw.for 
$(OBJDIR)/plcpower.o : plcpower.for 
$(OBJDIR)/plftmake.o : plftmake.for 
$(OBJDIR)/plcxtrac.o : plcxtrac.for 
$(OBJDIR)/idtcalc.o : idtcalc.for 
$(OBJDIR)/plcintro.o : plcintro.for 
$(OBJDIR)/tkbmmcrp.o : tkbmmcrp.for 
$(OBJDIR)/initcpl.o : initcpl.for 
$(OBJDIR)/lsinit.o : lsinit.for 
$(OBJDIR)/timido.o : timido.for 
$(OBJDIR)/plcgrad.o : plcgrad.for 
$(OBJDIR)/plmcalc.o : plmcalc.for 
$(OBJDIR)/plfmap.o : plfmap.for 
$(OBJDIR)/smoof1.o : smoof1.for 
$(OBJDIR)/plfiln.o : plfiln.for 
$(OBJDIR)/plcap.o : plcap.for 
$(OBJDIR)/plcparsr.o : plcparsr.for 
$(OBJDIR)/plcxntrp.o : plcxntrp.for 
$(OBJDIR)/glbsw.o : glbsw.for 
$(OBJDIR)/findstrg.o : findstrg.for 
$(OBJDIR)/findreal.o : findreal.for 
$(OBJDIR)/plcsinh.o : plcsinh.for 
$(OBJDIR)/grunlb2.o : grunlb2.for 
$(OBJDIR)/plcadd.o : plcadd.for 
$(OBJDIR)/resetd.o : resetd.for 
$(OBJDIR)/cplset.o : cplset.for 
$(OBJDIR)/smfunc.o : smfunc.for 
$(OBJDIR)/gettrng.o : gettrng.for 
$(OBJDIR)/plfmpi.o : plfmpi.for 
$(OBJDIR)/rp_geteq.o : rp_geteq.for 
$(OBJDIR)/findmltr.o : findmltr.for 
$(OBJDIR)/u_mks_add.o : u_mks_add.for 
$(OBJDIR)/plcacos.o : plcacos.for 
$(OBJDIR)/chr_toupper.o : chr_toupper.for 
$(OBJDIR)/ttintrp.o : ttintrp.for 
$(OBJDIR)/findmltl.o : findmltl.for 
$(OBJDIR)/findlog.o : findlog.for 
$(OBJDIR)/plc_error.o : plc_error.for 
$(OBJDIR)/plftmk4.o : plftmk4.for 
$(OBJDIR)/mgdelpkg.o : mgdelpkg.for 
$(OBJDIR)/mmxpnd.o : mmxpnd.for 
$(OBJDIR)/xinfac.o : xinfac.for 
$(OBJDIR)/plcmjr.o : plcmjr.for 
$(OBJDIR)/tkbry2rp.o : tkbry2rp.for 
$(OBJDIR)/pltimi.o : pltimi.for 
$(OBJDIR)/gttime.o : gttime.for 
$(OBJDIR)/pludlm.o : pludlm.for 
$(OBJDIR)/rpphelp.o : rpphelp.for 
$(OBJDIR)/plcdstar.o : plcdstar.for 
$(OBJDIR)/findmltc.o : findmltc.for 
$(OBJDIR)/findname.o : findname.for 
$(OBJDIR)/findint.o : findint.for 
$(OBJDIR)/initnws.o : initnws.for 
$(OBJDIR)/plcxcalc.o : plcxcalc.for 
$(OBJDIR)/plmmwx.o : plmmwx.for 
$(OBJDIR)/findintc.o : findintc.for 
$(OBJDIR)/rp_mks_conv.o : rp_mks_conv.for 
$(OBJDIR)/tmfllm.o : tmfllm.for 
$(OBJDIR)/abortt.o : abortt.for 
$(OBJDIR)/plsfadd.o : plsfadd.for 
$(OBJDIR)/plczcntr.o : plczcntr.for 
$(OBJDIR)/tkbrysrp.o : tkbrysrp.for 
$(OBJDIR)/plamgeo.o : plamgeo.for 
$(OBJDIR)/plsfsave.o : plsfsave.for 
$(OBJDIR)/pltmmfx.o : pltmmfx.for 
$(OBJDIR)/findintp.o : findintp.for 
$(OBJDIR)/plcsqrt.o : plcsqrt.for 
$(OBJDIR)/mgdelfun.o : mgdelfun.for 
$(OBJDIR)/plmgeo.o : plmgeo.for 
$(OBJDIR)/lsentr.o : lsentr.for 
$(OBJDIR)/nxptr.o : nxptr.for 
$(OBJDIR)/mrunlb2.o : mrunlb2.for 
$(OBJDIR)/ixchk0.o : ixchk0.for 
$(OBJDIR)/findeq.o : findeq.for 
$(OBJDIR)/plcprep.o : plcprep.for 
$(OBJDIR)/captl.o : captl.for 
$(OBJDIR)/plcdiff.o : plcdiff.for 
$(OBJDIR)/xintrp.o : xintrp.for 
$(OBJDIR)/mg_fixref.o : mg_fixref.for 
$(OBJDIR)/rpctini.o : rpctini.for 
$(OBJDIR)/timiun.o : timiun.for 
$(OBJDIR)/plcdelfn.o : plcdelfn.for 
$(OBJDIR)/plc_msgs.o : plc_msgs.for 
$(OBJDIR)/plckin.o : plckin.for 
$(OBJDIR)/plcerr.o : plcerr.for 
$(OBJDIR)/plcparse.o : plcparse.for 
$(OBJDIR)/plmmcv.o : plmmcv.for 
$(OBJDIR)/ndptr.o : ndptr.for 
$(OBJDIR)/iscal0.o : iscal0.for 
$(OBJDIR)/plabck.o : plabck.for 
$(OBJDIR)/plc_hand.o : plc_hand.for 
$(OBJDIR)/plmmdr.o : plmmdr.for 
$(OBJDIR)/plcfixup.o : plcfixup.for 
$(OBJDIR)/plc_smry.o : plc_smry.for 
$(OBJDIR)/plctype.o : plctype.for 
$(OBJDIR)/rxsclb.o : rxsclb.for 
$(OBJDIR)/readsnsc.o : readsnsc.for 
$(OBJDIR)/mgtryadd.o : mgtryadd.for 
$(OBJDIR)/plcxloc.o : plcxloc.for 
$(OBJDIR)/plammcv.o : plammcv.for 
$(OBJDIR)/plcmult.o : plcmult.for 
$(OBJDIR)/pltammt.o : pltammt.for 
$(OBJDIR)/rpxabbr.o : rpxabbr.for 
$(OBJDIR)/ixcal0.o : ixcal0.for 
$(OBJDIR)/plc_timi.o : plc_timi.for 
$(OBJDIR)/plccosh.o : plccosh.for 
$(OBJDIR)/pltmmt.o : pltmmt.for 
$(OBJDIR)/plcdfdt.o : plcdfdt.for 
$(OBJDIR)/plcfndsm.o : plcfndsm.for 
$(OBJDIR)/plceval.o : plceval.for 
$(OBJDIR)/mds_cache_disable.o : mds_cache_disable.for 
$(OBJDIR)/plccop.o : plccop.for 
$(OBJDIR)/tkbconrp.o : tkbconrp.for 
$(OBJDIR)/inirun.o : inirun.for 
$(OBJDIR)/fixgeo.o : fixgeo.for 
$(OBJDIR)/plclog.o : plclog.for 
$(OBJDIR)/plclog10.o : plclog10.for 
$(OBJDIR)/pljaco.o : pljaco.for 
$(OBJDIR)/uknot1.o : uknot1.for 
$(OBJDIR)/plcatan2.o : plcatan2.for 
$(OBJDIR)/plcgarg.o : plcgarg.for 
$(OBJDIR)/plcdiv.o : plcdiv.for 
$(OBJDIR)/tp2ord.o : tp2ord.for 
$(OBJDIR)/plcexp.o : plcexp.for 
$(OBJDIR)/plcbnd.o : plcbnd.for 
$(OBJDIR)/ixshft.o : ixshft.for 
$(OBJDIR)/plftmck.o : plftmck.for 
$(OBJDIR)/rp_hybrd1.o : rp_hybrd1.for 
