C******************** START FILE TP2ORD.FOR ; GROUP PLOTR1 ******************
C--------------------------------
C  UTILITY TO CALCULATE ORDER OF SCALAR MULTIGRAPH FUNCTIONS
C
      SUBROUTINE TP2ORD(ICT,IFUNK,ILOC,IKMASK)
C
      use cplotr_mod
C
      INTEGER IKMASK(NAXFOT)

C  ADD TO LIST OF FUNCTIONS TO BE PLOTTED, MAINTAINING INCREASING
C  ORDER

      ICM1=ICT-1
      IF(ICM1.EQ.0) GO TO 448
      DO 443 ICL=1,ICM1
         IF(IFUNK.LE.IABS(IFUNB(ICL,ILOC))) GO TO 444
 443  CONTINUE
      GO TO 448

 444  CONTINUE
      DO 445 ICJ=ICM1,ICL,-1
         ICJP1=ICJ+1
         IFUNB(ICJP1,ILOC)=IFUNB(ICJ,ILOC)
 445  CONTINUE
      IFUNB(ICL,ILOC)=IKMASK(IFUNK)
      GO TO 449

 448  CONTINUE
      IFUNB(ICT,ILOC)=IKMASK(IFUNK)

 449  CONTINUE
      IINTB(ILOC)=1
      INFB(ILOC)=ICT

      RETURN
      END
