C-----------------------------------------------------------------------
C  UKNOT1 -- RENORMALIZE A FUNCTION TO "KNOT" AT 1 AT SPECIFIED LOCATION
C
      SUBROUTINE UKNOT1(ZXKNOT,ZX,ZINPUT,INX,ZOUTPUT)
C
      REAL ZX(INX),ZINPUT(INX),ZOUTPUT(INX)
      REAL ZXKNOT(2)
C
C  ZXKNOT -- X LOCATION OR RANGE WHERE TO DO THE KNOT RENORMALIZATION
C       IF ZXKNOT(1).EQ.ZXKNOT(2) ITS A LOCATION O.W. ITS A RANGE
C       AND ZXKNOT(2).GT.ZXKNOT(1) IS EXPECTED.
C
C  ZX     -- X LOCATATIONS OF DATA
C  ZINPUT -- INPUT DATA AT X LOCATIONS
C    INX  -- NUMBER OF DATA POINTS
C
C  ZOUTPUT --  DATA AFTER RENORMALIZATION
C
C-----------------------------------------------------
C
      IF(INX.EQ.1) THEN
        ZOUTPUT(1)=1.0
        RETURN
      ENDIF
C
C  FIND LOCATION IN ZX OF ZXKNOT(1)
C
      DO 100 IX=1,INX-1
        IXP1=IX+1
        ZTEST=(ZX(IX)-ZXKNOT(1))*(ZX(IXP1)-ZXKNOT(1))
        IF(ZTEST.LE.0.0) GOTO 120
 100  CONTINUE
C
      IF(ZX(1).LT.ZX(INX)) THEN
        IF(ZXKNOT(1).LT.ZX(1)) THEN
          IKNOT=1
          ZFAC=0.0
        ELSE
          IKNOT=INX-1
          ZFAC=1.0
        ENDIF
      ENDIF
C
      IF(ZX(1).GE.ZX(INX)) THEN
        IF(ZXKNOT(1).GT.ZX(1)) THEN
          IKNOT=1
          ZFAC=0.0
        ELSE
          IKNOT=INX-1
          ZFAC=1.0
        ENDIF
      ENDIF
C
      GO TO 150
C
 120  CONTINUE
      IKNOT=IX
      ZFAC=0.0
      IF(ZX(IXP1).NE.ZX(IX))
     >    ZFAC=(ZXKNOT(1)-ZX(IX))/(ZX(IXP1)-ZX(IX))
C
 150  CONTINUE
      IF(ZXKNOT(2).EQ.ZXKNOT(1)) GO TO 400
C
C  WE DEAL WITH A RANGE OF LOCATIONS FOR COMPUTING THE NORMALIZATION
C
C
C  FIND LOCATION IN ZX OF ZXKNOT(2)
C
      DO 200 IX=1,INX-1
        IXP1=IX+1
        ZTEST=(ZX(IX)-ZXKNOT(2))*(ZX(IXP1)-ZXKNOT(2))
        IF(ZTEST.LE.0.0) GOTO 220
 200  CONTINUE
C
      IF(ZX(1).LT.ZX(INX)) THEN
        IF(ZXKNOT(2).LT.ZX(1)) THEN
          IKNOT2=1
          ZFAC2=0.0
        ELSE
          IKNOT2=INX-1
          ZFAC2=1.0
        ENDIF
      ENDIF
C
      IF(ZX(1).GE.ZX(INX)) THEN
        IF(ZXKNOT(2).GT.ZX(1)) THEN
          IKNOT2=1
          ZFAC2=0.0
        ELSE
          IKNOT2=INX-1
          ZFAC2=1.0
        ENDIF
      ENDIF
C
      GO TO 300
C
 220  CONTINUE
      IKNOT2=IX
      ZFAC2=0.0
      IF(ZX(IXP1).NE.ZX(IX))
     >    ZFAC2=(ZXKNOT(2)-ZX(IX))/(ZX(IXP1)-ZX(IX))
C
C  THE NORMALIZATION IS TO BE AVERAGED FROM A RANGE OF INPUT DATA
C
 300  CONTINUE
      IF(IKNOT.GT.IKNOT2) THEN
        ITEMP=IKNOT
        ZTEMP=ZFAC
        IKNOT=IKNOT2
        ZFAC=ZFAC2
        IKNOT2=ITEMP
        ZFAC2=ZTEMP
      ENDIF
C
      IF(IKNOT.EQ.IKNOT2) GO TO 410
C
      ZSUMFX=0.0
      ZSUMX=0.0
C
      DO 320 IK=IKNOT,IKNOT2
        IF(IK.EQ.IKNOT) THEN
          ZDX=ZX(IK+1)-(ZX(IK)+ZFAC*(ZX(IK+1)-ZX(IK)))
          ZFF=0.5*(ZFAC+1.0)
          ZF=ZINPUT(IK)+ZFF*(ZINPUT(IK+1)-ZINPUT(IK))
        ELSE IF(IK.EQ.IKNOT2) THEN
          ZDX=(ZX(IK)+ZFAC2*(ZX(IK+1)-ZX(IK)))-ZX(IK)
          ZFF=0.5*ZFAC
          ZF=ZINPUT(IK)+ZFF*(ZINPUT(IK+1)-ZINPUT(IK))
        ELSE
          ZDX=ZX(IK+1)-ZX(IK)
          ZF=0.5*(ZINPUT(IK+1)+ZINPUT(IK))
        ENDIF
C
        ZSUMX=ZSUMX+ZDX
        ZSUMFX=ZSUMFX+ZF*ZDX
C
 320  CONTINUE
C
      ZNORMI=ZSUMFX/ZSUMX
      IF(ZNORMI.EQ.0.0) THEN
        ZNORM=0.0
      ELSE
        ZNORM=1.0/ZNORMI
      ENDIF
C
      GO TO 450
C
C  THE NORMALIZATION IS JUST AT ONE LOCATION
C
 400  CONTINUE
      IKNOT2=IKNOT
      ZFAC2=ZFAC
C
C  .. OR TWO LOCATIONS WITHIN THE SAME INDEX INTERVAL
 410  CONTINUE
      ZNORMI=0.5*(
     >    ZINPUT(IKNOT)+ZFAC*(ZINPUT(IKNOT+1)-ZINPUT(IKNOT)) +
     >    ZINPUT(IKNOT2)+ZFAC2*(ZINPUT(IKNOT2+1)-ZINPUT(IKNOT2)) )
      IF(ZNORMI.EQ.0.0) THEN
        ZNORM=0.0
      ELSE
        ZNORM=1.0/ZNORMI
      ENDIF
C
C  APPLY RENORMALIZATION
C
 450  CONTINUE
      ZMAX=1.E35
      DO 500 IX=1,INX
        ZNORML=ZNORM
        IF(ABS(ZNORM).GT.1.0) THEN
          IF(ZMAX/ABS(ZNORM).LT.ABS(ZINPUT(IX))) THEN
            ZNORML=SIGN(1.0,ZNORM)*ZMAX/ABS(ZINPUT(IX))
          ENDIF
        ENDIF
        ZOUTPUT(IX)=ZINPUT(IX)*ZNORML
 500  CONTINUE
C
      RETURN
      END
