C******************** START FILE XINFAC.FOR ; GROUP IXCALC ******************
C---------------------------------------------------------------
C  XINFAC
C
C  CALCULATE INTERPOLATION FACTOR ON PASSED X ARRAY
C    USED IN REAL FCN XINTRP (SEE BELOW)
C
      SUBROUTINE XINFAC(ZXC,ICFAC,ZXA,INX,ZINTRP,ISTAT,IFLG)
C
C  INPUT
C  -----
C   ZXC-- CONSTANT X TO BE INTERPOLATED TO
C   ICFAC-- INTERPRETATION OF ZXC
C    =0:  ZXC IS IN UNITS OF X ARRAY
C    =1:  ZXC IS BETWEEN 0 AND 1 AND "INDICIAL", I.E. ZXC=0.0
C   REFERS TO START OF FIRST ZONE OF X ARRAY... ZXC=1.0 TO END OF
C   LAST ZONE OF X ARRAY
C    =2:  ZXC IS BETWEEN 0 AND 1 AND "NORMALIZED", I.E. THE DESIRED
C   LOCATION IS S.T. X/XMAX = ZXC
C    =3:  ZXC IS BETWEEN 0 AND 1 AND "RELATIVE", I.E. THE DESIRED
C    WHERE XMIN AND XMAX ARE THE MIN AND MAX VALUES IN THE X ARRAY
C
C   ZXA(INX)  THE X ARRAY, INX PTS
C
C   IFLG ZONE CTR/BDY SHIFT FLAG.  IF =1 USE THE X ARRAY AS IS;
C    IF =2 TREAT X ARRAY AS CORRESPONDING TO OUTER BDY OF ZONES;
C    DEFINE BY EXTRAPOLATION THE INNER BDY OF THE 1ST ZONE AND
C    TREAT THIS AS THE 1ST ELEMENT OF THE X ARRAY
C
C  OUTPUT
C  ------
C   ZINTRP = (IF IFLG=1) A VALUE BETWEEN 1.0 AND FLOAT(INX)
C       OR   (IF IFLG=2) A VALUE BETWEEN 0.0 AND FLOAT(INX)
C   LOCATING THE INTERPOLATION WITHIN THE X ARRAY
C
C  ISTAT = 0  NORMAL SUCCESSFUL COMPLETION
C        = 1 (POSSIBLE IF ICFAC= 0 OR 2)  SPECIFIED ZXC IS LESS THAN
C   THE MINIMUM X IN THE X ARRAY
C        = 2 (POSSIBLE IF ICFAC= 0) SPECIFIED ZXC IS GREATER THAN
C   THE MAXIMUM X IN THE X ARRAY
C        = 3 (POSSIBLE IF ICFAC= 0 1 OR 2)  SPECIFIED ZXC DOES NOT
C   CONFORM TO A UNIQUE LOCATION IN THE X ARRAY
C
      DIMENSION ZXA(INX)
C
C  EXECUTABLE CODE
C
C  DEAL WITH INDICIAL MAP (ICFAC=1)
C
      ISTAT=0
      IF(ICFAC.NE.1) GO TO 100
C
      IF(IFLG.EQ.1) ZINTRP=1.0+FLOAT(INX)*ZXC
      IF(IFLG.EQ.2) ZINTRP=FLOAT(INX)*ZXC
      RETURN
C
 100  CONTINUE
C  IF IFLG=2 DEFINE INNER ZONE
      ZXIBDY=ZXA(1)
      IF(IFLG.EQ.2) ZXIBDY=ZXA(1)-(ZXA(2)-ZXA(1))
C
C
C  DEFINE TARGET IN ABSOLUTE X UNITS
C
      IF(ICFAC.EQ.0) THEN
        ZTARG=ZXC
      ELSE IF(ICFAC.EQ.2) THEN
        ZNORM=ZXIBDY
        DO 110 IX=1,INX
          IF(ABS(ZXA(IX)).LT.ABS(ZNORM)) GO TO 110
          ZNORM=ZXA(IX)
110     CONTINUE
        ZTARG=ZXC*ZNORM
      ENDIF
C  FIND MIN AND MAX OF X ARRAY
        ZXMIN=ZXIBDY
        ZXMAX=ZXIBDY
        DO 120 IX=1,INX
          ZXMIN=AMIN1(ZXMIN,ZXA(IX))
          ZXMAX=AMAX1(ZXMAX,ZXA(IX))
 120    CONTINUE
      IF(ICFAC.EQ.3) ZTARG=ZXMIN+ZXC*(ZXMAX-ZXMIN)
C
C  BOUNDS CHECK
C
      IF(ZTARG.LT.ZXMIN) THEN
        ISTAT=1
        ZINTRP=1.0
        IF(IFLG.EQ.2) ZINTRP=0.0
        RETURN
      ELSE IF(ZTARG.GT.ZXMAX) THEN
        ISTAT=2
        ZINTRP=FLOAT(INX)
        RETURN
      ELSE IF(ZXMIN.EQ.ZXMAX) THEN
        ISTAT=3
        RETURN
      ENDIF
C
C  LOOK FOR TARGET INTERSECTIONS
C
      ITARG=0
C  REMEMBER X MAY NOT BE MONOTONIC
      IF((IFLG.EQ.2).AND.
     >  ( ((ZXIBDY.LE.ZTARG).AND.(ZTARG.LT.ZXA(1))) .OR.
     >    ((ZXIBDY.GE.ZTARG).AND.(ZTARG.GT.ZXA(1))) ) ) THEN
        ITARG=1
        ZINTRP=(ZTARG-ZXIBDY)/(ZXA(1)-ZXIBDY)
      ENDIF
C
      INXM1=INX-1
      DO 200 IX=1,INXM1
      IXP1=IX+1
      Z1=ZXA(IX)
      Z2=ZXA(IXP1)
      IF( ((Z1.LE.ZTARG).AND.(ZTARG.LT.Z2)) .OR.
     >      ((Z1.GE.ZTARG).AND.(ZTARG.GT.Z2)) ) THEN
        IF(ITARG.EQ.1) THEN
          ISTAT=3
          RETURN
        ENDIF
        ITARG=1
        ZINTRP=FLOAT(IX)+(ZTARG-Z1)/(Z2-Z1)
      ENDIF
 200  CONTINUE
C  CHECK LAST X PT.
      IF(ZTARG.EQ.ZXA(INX)) THEN
        IF(ITARG.EQ.1) THEN
          ISTAT=3
          RETURN
        ENDIF
        ITARG=1
        ZINTRP=FLOAT(INX)
      ENDIF
C  GOT IT
      RETURN
      END
C******************** END FILE XINFAC.FOR ; GROUP IXCALC ******************
