$(OBJDIR)/f90_link2.o : f90_link2.for 
$(OBJDIR)/mcrdr_open.o : mcrdr_open.for 
$(OBJDIR)/mcrdr_openwr.o : mcrdr_openwr.for 
$(OBJDIR)/mcrdr_rdnb.o : mcrdr_rdnb.for 
$(OBJDIR)/mcrdr_rdss2.o : mcrdr_rdss2.for 
$(OBJDIR)/mcrdr_rdss.o : mcrdr_rdss.for 
$(OBJDIR)/mcrdr_read.o : mcrdr_read.for 
$(OBJDIR)/mcsort_ch_ord.o : mcsort_ch_ord.for 
$(OBJDIR)/mcsort_insert.o : mcsort_insert.for 
$(OBJDIR)/mcsort_order.o : mcsort_order.for 
$(OBJDIR)/mcstr_capit.o : mcstr_capit.for 
$(OBJDIR)/mcstr_clear.o : mcstr_clear.for 
$(OBJDIR)/mcstr_dlimw.o : mcstr_dlimw.for 
$(OBJDIR)/mcstr_findnc.o : mcstr_findnc.for 
$(OBJDIR)/mcstr_findnd.o : mcstr_findnd.for 
$(OBJDIR)/mcstr_index.o : mcstr_index.for 
$(OBJDIR)/mcstr_insert.o : mcstr_insert.for 
$(OBJDIR)/mcstr_lastnb.o : mcstr_lastnb.for 
$(OBJDIR)/mcstr_lastx.o : mcstr_lastx.for 
$(OBJDIR)/mcstr_lcase.o : mcstr_lcase.for 
$(OBJDIR)/mcstr_wordlim.o : mcstr_wordlim.for 
