      SUBROUTINE MCRDR_RDNB(LUN,LINE,IEOF)
C
C  READ TO FIRST NON-BLANK LINE, EOF CHECK
C
      CHARACTER*(*) LINE
C
      IEOF=0
 10   CONTINUE
      CALL MCRDR_READ(LUN,LINE,IEOF)
      IF(IEOF.EQ.1) GO TO 20
C
      INB=MCSTR_FINDND(LINE,' ')
      IF(INB.EQ.0) GO TO 10
C
 20   CONTINUE
C
      RETURN
      END
