      SUBROUTINE MCRDR_RDSS2(LUN,LINE,SUBSTR1,SUBSTR2,IN1,IN2,IEOF)
C
C  READ TO FIRST LINE CONTAINING EITHER OF TWO
C   SUBSTRINGS; EOF CHECK
C
      CHARACTER*(*) LINE
      CHARACTER*(*) SUBSTR1,SUBSTR2
C
      IEOF=0
 10   CONTINUE
      CALL MCRDR_READ(LUN,LINE,IEOF)
      IF(IEOF.EQ.1) GO TO 20
C
      IN1=INDEX(LINE,SUBSTR1)
      IN2=INDEX(LINE,SUBSTR2)
      IF((IN1.EQ.0).AND.(IN2.EQ.0)) GO TO 10
C
 20   CONTINUE
C
      RETURN
      END
