      SUBROUTINE MCRDR_OPENWR(LUN,NAME)
C
C  OPEN A FILE FOR *WRITE* ASCII SEQUENTIAL
C
      CHARACTER*(*) NAME
C
      CLOSE(UNIT=LUN,ERR=5)
 5    CONTINUE
C
      OPEN(UNIT=LUN,FILE=NAME,status='NEW',ACCESS='SEQUENTIAL')
C
      RETURN
      END
