      SUBROUTINE MCRDR_RDSS(LUN,LINE,SUBSTR,INSUB,IEOF)
C
C  READ TO FIRST LINE CONTAINING "SUBSTR", EOF CHECK
C
      CHARACTER*(*) LINE
      CHARACTER*(*) SUBSTR
C
      IEOF=0
 10   CONTINUE
      CALL MCRDR_READ(LUN,LINE,IEOF)
      IF(IEOF.EQ.1) GO TO 20
C
      INSUB=INDEX(LINE,SUBSTR)
      IF(INSUB.EQ.0) GO TO 10
C
 20   CONTINUE
C
      RETURN
      END
