      SUBROUTINE MCSTR_INSERT(STR1,STR2)
C
C  INSERT STR1 LEFT JUSTIFIED IN STR2
C  IF STR1 IS SHORTER THAN STR2, STR2 IS PADDED WITH BLANKS
C  IF STR2 IS LONGER THAN STR2 A TRUNCATED VSN OF STR1 IS INSERTED
C
      CHARACTER*(*) STR1
      CHARACTER*(*) STR2
C
      L1=LEN(STR1)
      L2=LEN(STR2)
C
      L=MIN0(L1,L2)
C
      STR2(1:L)=STR1(1:L)
C
      IF(L.LT.L2) THEN
        DO 10 IL=L+1,L2
          STR2(IL:IL)=' '
 10     CONTINUE
      ENDIF
C
      RETURN
      END
