      SUBROUTINE MCSTR_DLIMW(LINE,I,CHAR,IW1,IW2)
C
C  SIMILAR TO MCSTR_WORDLIM BUT WITHOUT ERROR CHECK AND
C  ONLY ONE DELIMITER SPECIFIED
C
      CHARACTER*(*) LINE
      CHARACTER*1 CHAR
C
      L=LEN(LINE)
C
      IW1=MAX0(1,(MCSTR_LASTX(LINE(1:I),CHAR)+1))
C
      I2=INDEX(LINE(I:L),CHAR)
      IF(I2.EQ.0) I2=L+2
      IW2=MIN0(L,(I+I2-2))
C
      RETURN
      END
