      INTEGER FUNCTION MCSTR_FINDNC(STR,CHAR)
C
C  FIND FIRST CHARACTER IN STR WHICH IS .NE. CHAR
C
      CHARACTER*(*) STR
      CHARACTER*1 CHAR
C
      L=LEN(STR)
      DO 10 I=1,L
        IF(STR(I:I).NE.CHAR) GO TO 20
 10   CONTINUE
C
C  NOT FOUND
C
      I=0
C
C  FOUND
C
 20   CONTINUE
      MCSTR_FINDNC=I
      RETURN
      END
