      INTEGER FUNCTION MCSTR_FINDND(STR,DLIST)
C
C  FIND FIRST CHARACTER IN STR WHICH IS *NOT* ANY OF THE CHARACTERS
C  IN DELIMITER LIST DLIST
C
C  RETURN ZERO IF ALL CHARACTERS IN STR ARE ALSO IN DLIST
C
      CHARACTER*(*) STR
      CHARACTER*(*) DLIST
C
      L=LEN(STR)
      ND=LEN(DLIST)
C
      IFIRST=0
C
      DO 20 I=1,L
        DO 10 ID=1,ND
          IF(STR(I:I).EQ.DLIST(ID:ID)) GO TO 20
 10     CONTINUE
C  FOUND
        IFIRST=I
        GO TO 30
C
 20   CONTINUE
C
 30   CONTINUE
      MCSTR_FINDND=IFIRST
      RETURN
      END
