#GNU Makefile to build Library librplot_mod.a 
#
#08/01/00 C. Ludescher
#
ifneq ($(MAKELEVEL),0)
# if OBJ was defined for main Makefile one level down
ifeq ("${OBJ}",".")
	override OBJ=..
endif
endif

# define system dependent flags, etc.
-include ../share/Make.local
include ../share/Make.flags

ifdef DEBUG
	F90FLAGS = $(DF90FLAGS)
	FFLAGS = $(DFFLAGS)
endif

ARC = $(OBJ)/lib/librplot_mod.a
OBJDIR = $(OBJ)/obj/rplot_mod

INCFLAGS := $(INCFLAGS) $(IOPT)$(NETCDF_DIR)/include

#=============================================================
# f90 modules
#public Module names
Mnams = cplotr_mod.mod extrac2_mod.mod mfblok_mod.mod nltrdat_mod.mod plfmpa_mod.mod rpcalc_mod.mod

# source file names
Mobjs = cplotr_mod.o extrac2_mod.o mfblok_mod.o nltrdat_mod.o plfmpa_mod.o rpcalc_mod.o

MODS = $(foreach file,$(Mobjs),$(ARC)($(file)))

ifeq ($(MODUP),Y)
 MODS0=$(foreach m,$(Mnams),$(shell  echo $(m) | tr 'a-z' 'A-Z'))
 MODULES=$(foreach m,$(MODS0),$(subst .MOD,.$(MODEXT),$(m)))
else
 MODULES = $(foreach m,$(Mnams),$(subst .mod,.$(MODEXT),$(m)))
endif 

# fortran archive members
F  = $(subst .f,.o, $(wildcard *.f)) $(subst .F,.o, $(wildcard *.F))
F90 = $(subst .f90,.o, $(wildcard *.f90)) $(subst .F90,.o, $(wildcard *.F90))
FALL = $(F) $(F90)
MEM = $(foreach file,$(FALL),$(ARC)($(file)))


.PHONY: clean realclean checkdir all exec

libs: FORCE $(ARC)

all:  libs 
	@echo done  

$(OLDLIB): timestamp.inf
	@echo "--- DETECTED rplot_mod.a source update"
	@echo "--- Re-Making $(ARC)"
	@$(MAKE) libs

FORCE:
	@test -d $(OBJ)/lib || mkdir -p $(OBJ)/lib
	@test -d $(OBJ)/obj/rplot_mod || mkdir -p $(OBJ)/obj/rplot_mod

$(ARC): $(MODS) $(MEM)
	@$(RANLIB) $@ > /dev/null

# compile 
$(ARC)(%.o): %.f
	$(FC) $(FFLAGS) $(MODFLAGS) -I./ $(INCFLAGS) $(OUT)  $(OBJDIR)/$*.o $<
	$(make_ar)

$(ARC)(%.o): %.f90
	$(FC90) $(FFLAGS) $(MODFLAGS) -I./ $(INCFLAGS) $(OUT) $(OBJDIR)/$*.o $<
	$(make_ar)

# pre-process/compile fixed fortran code
$(ARC)(%.o): %.F
	$(F_proc)
	$(make_ar)

#
#---------------------------------------------------
exec:
	@echo 

clean: 
	@rm -f $(OBJDIR)/*

realclean: clean
	@rm -f $(ARC)

install:
	@test -d $(LIBDIR) || mkdir -p $(LIBDIR)
	@if test -f $(ARC); then \
	  umask 133; cp $(ARC) $(LIBDIR)/; \
	else test -f $(LIBDIR)/librplot_mod.a || echo ">>> can not find $(ARC)";fi

uninstall:
	rm -f $(LIBDIR)/librplot_mod.a
