C------------------------------------------------------------------
C  MFWBLK - WRITE 512 BYTE BLOCKED "MF.PLN" BINARY FILE FOR RPLOT
C
C  APR 1987 DMC - MF FILE RE-ORGANIZED FOR FASTER ACCESS
C    FIXED LENGTH 512 BYTE RECORDS
C    STRUCTURE:
C     [HEADER BLOCKS...
C        # FCNS
C        # TIME PTS
C        # BLOCK ADDRESS, TIME VECTOR
C        # BLOCK ADDRESS OF EACH FCN...]
C     [TIME VECTOR BLOCK(S)]
C     [DATA FUNCTION BLOCKS]
C
C  THE ENTIRE TIME VARIATION OF EACH FCN IS STORED IN A CONTIGUOUS
C  SET OF BLOCKS.  EACH DATA FCN'S 1ST WORD IS STORED AT THE START OF
C  A 512 BYTE BLOCK.
C
C  NOTE THE HEADER DOES NOT CONTAIN A COMPLETE DESCRIPTION OF THE DATA
C  ADDL NEEDED INFORMATION IS STORED IN THE "TF.PLN" FILE; CF RPLOT
C  SYSTEM
C
C--------------------------------------------------
C
      SUBROUTINE MFWBLK(LUNI,LUNMF,IVEC,ISIZ,IER)
C
C--------------------------------------------------
C
C  LUNI - LUN OF OPEN FILE OF "OLD" MF FORMAT (USUALLY FIXED LENGTH
C   80 BYTE RECORDS, FCN DATA NOT CONTIGUOUSLY STORED; WILL BE ACCESSED
C   VIA LIBRARY SUBROUTINES)
C
C  LUNMF - LUN OF OPEN FILE - MF FILE TO WRITE
C
C  IVEC(ISIZ) DATA FCN ADDRESSING INFORMATION (CF POPLOT.FOR, CALLER)
C
C  IER = 0 ON EXIT - NORMAL SUCCESSFUL COMPLETION
C        ERROR OTHERWISE...
C
C--------------------------------------------------
C
      use datmgr_mod  ! DATA STORAGE BLOCK
      use cplotr_mod  ! RPLOT COMMON
      use mfblok_mod
C
      INTEGER IVEC(ISIZ)
C
C--------------------------------------------------
C  STATEMENT FCN - WDS TO BLOCKS -
C
      IBLOKS(IWORDS)=1+(IWORDS-1)/IBLOCK
C
C  INITIALIZE CONNECTION TO OLD STYLE MF FILE
C
      MFBLKI=.FALSE.  ! SIGNAL INPUT VIA "OLD" FORMAT FILE
      MFLUNI=LUNI
C
      irecsz=nblkfac(ierr)*nzones
      CLOSE(UNIT=MFLUNI)
C
C unix changes -- DMC 1 Jul 1992
C
      irunid=index(runid,' ')-1
      if(irunid.le.0) irunid=len(runid)
      OPEN(UNIT=MFLUNI,FILE=RUNID(1:IRUNID)//'BF.PLN',
     >    ACCESS='DIRECT',STATUS='OLD',RECL=irecsz)
C
C--------------------------------------------------
C  CONSTRUCT HEADER
C
      IBLOCK=IBLKSZ
C
C  IVEC(1) GIVES NO. OF FCNS
C  IVEC(2) GIVES NO. OF TIME PTS
      ISIZH=IVEC(1)+3+IBLKSZ/8
      IBLOKH=IBLOKS(ISIZH)  ! HEADER SIZE IN BLOCKS
C
C  IVEC(3) SET TO BLOCK ADDRESS OF TIME VECTOR
      IVEC(3)=IBLOKH+1
C
      IBLOKT=IBLOKS(IVEC(2))  ! TIME VECTOR SIZE IN BLOCKS
      IF(IBLOKT.LE.0) THEN
        IER=1
        write(6,*) ' ?MFWBLK:  NO TIME VECTOR DATA'
        RETURN
      ENDIF
C
      INEXT=IVEC(3)+IBLOKT    ! BLOCK ADDRESS OF NEXT DATA FCN
C
      DO IFCN=1,IVEC(1)
        IFI=IFCN+3
        IWDS=IVEC(IFI)*IVEC(2)
        IVEC(IFI)=INEXT
        IBLOKD=IBLOKS(IWDS)  ! DATA FCN SIZE IN BLOCKS
        INEXT=IVEC(IFI)+IBLOKD
      ENDDO
C
      IVEC(IFI+1)=INEXT      ! PTS BEYOND END OF DATA FILE
C
C  WRITE THE HEADER - WRITE IBLOKH*IBLOCK WORDS
C  THE LAST FEW WORDS ARE SPARES
C
      IPREV=0
      DO IREC=1,IBLOKH
        IWD1=IPREV+1
        IWD2=IBLOCK*IREC
        IRECMF=IREC
        WRITE(LUNMF,REC=IRECMF) (IVEC(II),II=IWD1,IWD2)
        IPREV=IWD2
      ENDDO
C
C--------------------------------------------------
C  READ,WRITE THE TIME VECTOR
C
      CALL GETTM3(IER,IVEC(2))
C
C  THE EXPECTED NUMBER OF TIME PTS MUST COME BACK
      IF((IER.NE.0).OR.(NTR.NE.IVEC(2))) THEN
        write(6,*) ' ?MFWBLK:  ERROR ON READBACK OF MF TIME VECTOR'
        IER=1
        RETURN
      ENDIF
C
      CALL MFWPUT(LUNMF,IRECMF,TIME3,NTR)
C
C
C--------------------------------------------------
C  READ,WRITE THE DATA
C
      CALL DMGINI
C
C  FIRST WORKSPACE
      ISIZE1=NR0
      CALL DMGALO(ISIZE1,JLOC,10)
C  RESERVE THE ALLOCATED SPACE FOR LATER USE
      NWDS(JLOC)=ISIZE1
      DMGLBL(JLOC)='%WRK1'
C
      DO IF=1,NFXT
C
        IFI=IF+3
        IFIP=IFI+1
C
        CALL DMGFXT(IF,IND)
        IBLOKZ=IBLOKS(NWDS(IND))
C
        IF(IBLOKZ.NE.(IVEC(IFIP)-IVEC(IFI))) THEN
          write(6,*) ' ?MFWBLK:  UNEXPECTED DATA FCN SIZE ON READBACK:'
          write(6,*) NWDS(IND),DMGLBL(IND)
          IER=1
          RETURN
        ENDIF
C
        MPRIO(IND)=1
C
        CALL MFWPUT(LUNMF,IRECMF,DATBUF(LOCD(IND)),NWDS(IND))
C
      ENDDO
C
      IER=0
      RETURN
      END
