C******************** START FILE MOMRUN.FOR ; GROUP PLOTMM ******************
C
C-----------------------------------------------------------------
C
      LOGICAL FUNCTION MOMRUN(INUM,IGEO)
C
C  THIS FCN RETURNS .TRUE. IF THE TRANSP RUN DATA CURRENTLY BEING
C  ACCESSED CONTAINS A MOMENTS DESCRIPTION OF THE PLASMA EQUILIBRIUM,
C  .FALSE. OTHERWISE
C
C  DMC 31 MAR 1994 -- OUTPUT ARGUMENT IGEO ADDED
C    IF MOMRUN RETURNS .TRUE., THEN...
C        IGEO=0 MEANS A SYMMETRIC MOMENTS GEOMETRY
C        IGEO=1 MEANS AN ASYMMETRIC MOMENTS GEOMETRY
C
C
C  COMMON BLOCKS---
C
      use datmgr_mod
      use cplotr_mod
C---
      LOGICAL FUNGOT,IGOT
C
C
C  IF THE FCN "RMM00" IS IN THE VS. (X,T) TRANSP PLOTTING OUTPUT, THEN
C  THE MOMENTS DESCRIPTION IS AVAILABLE
C
C  Symmetric Moments?
C
      IGEO=0
      PLTABB='RMM00'
C
      IGOT=FUNGOT(INUM)
C
      IF(.NOT.IGOT) THEN
C
C  ASYMMETRIC MOMENTS?
C
        IGEO=1
        PLTABB='RMC00'
C
        IGOT=FUNGOT(INUM)
      ENDIF
C
      MOMRUN=IGOT
C
      RETURN
      END
C******************** END FILE MOMRUN.FOR ; GROUP PLOTMM ******************
