$(OBJDIR)/wkbuf_mod.o : wkbuf_mod.f90 
$(OBJDIR)/mds_clear_save.o : mds_clear_save.f90 
$(OBJDIR)/mds_cache_dev_io.o : mds_cache_dev_io.f90 
$(OBJDIR)/mds_cache_tio.o : mds_cache_tio.f90 
$(OBJDIR)/tfilrd.o : tfilrd.for 
$(OBJDIR)/vprotec.o : vprotec.for 
$(OBJDIR)/mds_cache_read.o : mds_cache_read.for 
$(OBJDIR)/tfilnd.o : tfilnd.for 
$(OBJDIR)/mftimrd.o : mftimrd.for 
$(OBJDIR)/mds_cache_init.o : mds_cache_init.for 
$(OBJDIR)/tfilop.o : tfilop.for 
$(OBJDIR)/tfilw2.o : tfilw2.for 
$(OBJDIR)/dmgfxt.o : dmgfxt.for 
$(OBJDIR)/mdsnfrd.o : mdsnfrd.for 
$(OBJDIR)/timck1.o : timck1.for 
$(OBJDIR)/rp_dmgalo.o : rp_dmgalo.for 
$(OBJDIR)/zermsg.o : zermsg.for 
$(OBJDIR)/nfread.o : nfread.for 
$(OBJDIR)/fungot.o : fungot.for 
$(OBJDIR)/mds_cache_list.o : mds_cache_list.for 
$(OBJDIR)/mds_cache_active.o : mds_cache_active.for 
$(OBJDIR)/plprio.o : plprio.for 
$(OBJDIR)/tfsclab.o : tfsclab.for 
$(OBJDIR)/cdfmfrd.o : cdfmfrd.for 
$(OBJDIR)/mfwblk.o : mfwblk.for 
$(OBJDIR)/plnames.o : plnames.for 
$(OBJDIR)/mds_cache_write.o : mds_cache_write.for 
$(OBJDIR)/cdfilop.o : cdfilop.for 
$(OBJDIR)/mfinq.o : mfinq.for 
$(OBJDIR)/plmmrd.o : plmmrd.for 
$(OBJDIR)/pbinrd.o : pbinrd.for 
$(OBJDIR)/cdfnfrd.o : cdfnfrd.for 
$(OBJDIR)/plmmrls.o : plmmrls.for 
$(OBJDIR)/mfprio.o : mfprio.for 
$(OBJDIR)/mdstrd.o : mdstrd.for 
$(OBJDIR)/dmgfot.o : dmgfot.for 
$(OBJDIR)/set_rpluns.o : set_rpluns.for 
$(OBJDIR)/arc_chk.o : arc_chk.for 
$(OBJDIR)/mfwput.o : mfwput.for 
$(OBJDIR)/dmgfotx.o : dmgfotx.for 
$(OBJDIR)/mdshrd.o : mdshrd.for 
$(OBJDIR)/xrunlb2.o : xrunlb2.for 
$(OBJDIR)/mfhdrd.o : mfhdrd.for 
$(OBJDIR)/tfilr2.o : tfilr2.for 
$(OBJDIR)/tfilhd.o : tfilhd.for 
$(OBJDIR)/cdfhrd.o : cdfhrd.for 
$(OBJDIR)/momrun.o : momrun.for 
$(OBJDIR)/copyr4.o : copyr4.for 
$(OBJDIR)/mds_cache_fname.o : mds_cache_fname.for 
$(OBJDIR)/dmgxot.o : dmgxot.for 
$(OBJDIR)/mds_connect.o : mds_connect.for 
$(OBJDIR)/aordr.o : aordr.for 
$(OBJDIR)/pbinwr.o : pbinwr.for 
$(OBJDIR)/mdsmfrd.o : mdsmfrd.for 
$(OBJDIR)/initcf.o : initcf.for 
$(OBJDIR)/dmggeo.o : dmggeo.for 
$(OBJDIR)/rpcaldat.o : rpcaldat.for 
$(OBJDIR)/tfilwr.o : tfilwr.for 
$(OBJDIR)/cdfilcl.o : cdfilcl.for 
$(OBJDIR)/readmf.o : readmf.for 
$(OBJDIR)/gettm3.o : gettm3.for 
$(OBJDIR)/iniwrk.o : iniwrk.for 
