C******************** START FILE TFILHD.FOR ; GROUP TFILIO *************
C-----------------------------------------------------------------
C  SUBROUTINE TFILHD
C
C  READ/WRITE HEADER (FIRST RECORD) * SEPERATE ROUTINE DMC NOV 1984
C  KLUGE STUFF RECORD TO ALLOW 6 DIGIT SHOT NO., BUT ALSO BE ABLE
C  TO READ OLD FILES!
C
C  MODIF DMC JUNE 1985 - RUN ID IS 6 CHAR STRING - REPLACING RUN NO.
C  BUT CONTINUE TO SUPPORT THEM OLD FILES
C
      SUBROUTINE TFILHD(LUN,NRUN,
     >      RUNID,NSHOT,NZONES,NFT,NFR,NXR,IWRITE,FMT)
C
      CHARACTER*10 ZTEMP
      CHARACTER*10 RUNID
C
      CHARACTER*3 FMT
C
      CHARACTER*14 ZTEMP2
C
C----------------------------------------
C
      IF(IWRITE.EQ.1) THEN
C
        NRUN=-1
        WRITE(LUN,2001) NRUN,NSHOT,NZONES,NFT,NFR,NXR,RUNID,FMT
 2001 FORMAT(I4,I6,4I5,A10,1X,A3)
C
      ELSE
C
C  READ HAS "HYSTERESIS EFFECT"
C   USE FACT THAT **ALL** TRANSP RUN NUMBERS HAVE PRECISELY 4 DIGITS
C   (NONE HAVE 3, NONE HAVE 5 DIGIT RUN NUMBERS)
C   THUS DISTINGUISH OLD AND NEW FORMATS BY CHECKING IF 1ST CHAR IS
C   BLANK
C
C... JUNE 1985: MORE "HYSTERESIS":  NRUN=-1 MEANS NEW FILES WHERE RUNS
C  ARE IDENTIFIED BY 6 CHAR RUNID VARIABLES.
C
C... MARCH 1990:  SUPPORTING UP TO 8 CHARACTER RUNIDS NOW.
C... Aug 1996:  supporting up to 10 character runids now.
C
        FMT=' '
        RUNID=' '
C
        READ(LUN,2002) ZTEMP,NZONES,NFT,NFR,NXR,ZTEMP2
 2002 FORMAT(A10,4I5,A14)
C
C  NEW FORMAT
        IF(ZTEMP(1:4).EQ.'  -1') THEN
          READ(ZTEMP,'(4X,I6)') NSHOT
C
C  DECODE RUNID AND FMT FROM ZTEMP2 STRING
C    RUNID IS THE FIRST BLANK DELIMITTED WORD
C    FMT (IF PRESENT) IS THE SECOND BLANK DELIMITTED WORD
C    ALG. WORKS FOR OLD 6 CHAR RUNID OR NEW 8 CHAR RUNID
C
          IBL=INDEX(ZTEMP2,' ')
          RUNID=ZTEMP2(1:IBL-1)
          ILTMP2=LEN(ZTEMP2)
          DO 10 IC=IBL,ILTMP2
            IF(ZTEMP2(IC:IC).NE.' ') GO TO 11
 10       CONTINUE
          IC=ILTMP2
 11       CONTINUE
          FMT=ZTEMP2(IC:MIN0(ILTMP2,IC+2))
C
        ELSE IF(ZTEMP(1:1).EQ.' ') THEN
C  OLD OLD FORMAT
          READ(ZTEMP,'(I5,I5)') NRUN,NSHOT
          WRITE(RUNID,'(I4,4X)') NRUN
        ELSE
C  OLD NEW FORMAT
          READ(ZTEMP,'(I4,I6)') NRUN,NSHOT
          WRITE(RUNID,'(I4,4X)') NRUN
C
        ENDIF
        NRUN=-1
C
      ENDIF
C
      RETURN
      END
C******************** END FILE TFILHD.FOR ; GROUP TFILIO ***************
