      SUBROUTINE TFILND(UNITS)
      CHARACTER*(*) UNITS
C
C  REMOVE "$" FROM TFILIO UNITS LABELS
C
 100  CONTINUE
        INDOL=INDEX(UNITS,'$')
        IF(INDOL.EQ.0) GO TO 120
        UNITS(INDOL:INDOL)=' '
        GO TO 100
 120  CONTINUE
C
      RETURN
      END
