C******************** START FILE DMISTA.FOR ; GROUP DATMGR ******************
C-------------------------------------------------------------
C  DMISTA
C
C  RETURN STATS ON SPECIFIED SLOT J
C
C   IL=PTR IN DATA BUFFER TO FIRST WORD OF UNUSED SPACE PRECEDING
C   DATA OF ENTRY J
C   IN=TOTAL SIZE OF DATA OF ENTRY J + SURROUNDING UNUSED SPACE
C   INPREV= NUMBER OF WORDS OF UNUSED SPACE PRECEDING ENTRY J DATA
C   INNEXT= NUMBER OF WORDS OF UNUSED SPACE FOLLOWING ENTRY J DATA
C
      SUBROUTINE DMISTA(J,IL,IN,INPREV,INNEXT)
C
      use datmgr_mod
C
      JPRE=LPREV(J)
      IL=LOCD(JPRE)+NWDS(JPRE)
      INPREV=LOCD(J)-IL
      JNEX=LNEXT(J)
      INNEXT=LOCD(JNEX)-(LOCD(J)+NWDS(J))
      IN=INPREV+INNEXT+NWDS(J)
      RETURN
      	END
C******************** END FILE DMISTA.FOR ; GROUP DATMGR ******************
